//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yaguang.VJK3G {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager _instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yaguang.VJK3G.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC6651开关量数据输出错误。.
        /// </summary>
        internal static string StringAC6651DataOutError {
            get {
                return ResourceManager.GetString("StringAC6651DataOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化AC6651错误。.
        /// </summary>
        internal static string StringAC6651OpenError {
            get {
                return ResourceManager.GetString("StringAC6651OpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置AC6651端口模式出错。.
        /// </summary>
        internal static string StringAC6651SetPortIOModeError {
            get {
                return ResourceManager.GetString("StringAC6651SetPortIOModeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置timer数据出错。.
        /// </summary>
        internal static string StringAC6651SetTimerDataError {
            get {
                return ResourceManager.GetString("StringAC6651SetTimerDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置timer模式出错。.
        /// </summary>
        internal static string StringAC6651SetTimerModeError {
            get {
                return ResourceManager.GetString("StringAC6651SetTimerModeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化矢网失败，请检查矢网。.
        /// </summary>
        internal static string StringAVOpenError {
            get {
                return ResourceManager.GetString("StringAVOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        internal static string StringErrorTitle {
            get {
                return ResourceManager.GetString("StringErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化示波器失败，请检查示波器。.
        /// </summary>
        internal static string StringOSCOpenError {
            get {
                return ResourceManager.GetString("StringOSCOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非法的PortNo值。.
        /// </summary>
        internal static string StringPortNoOutOfRange {
            get {
                return ResourceManager.GetString("StringPortNoOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 初始化pcio卡错误，请检查pcio卡。.
        /// </summary>
        internal static string StringSCOpenError {
            get {
                return ResourceManager.GetString("StringSCOpenError", resourceCulture);
            }
        }
    }
}
