//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yaguang.VJK3G.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ItemRXNaiGongLuChecked {
            get {
                return ((bool)(this["ItemRXNaiGongLuChecked"]));
            }
            set {
                this["ItemRXNaiGongLuChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ItemRXZhuBoChecked {
            get {
                return ((bool)(this["ItemRXZhuBoChecked"]));
            }
            set {
                this["ItemRXZhuBoChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ItemRXChaSunChecked {
            get {
                return ((bool)(this["ItemRXChaSunChecked"]));
            }
            set {
                this["ItemRXChaSunChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ItemRXGeLiDuChecked {
            get {
                return ((bool)(this["ItemRXGeLiDuChecked"]));
            }
            set {
                this["ItemRXGeLiDuChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ItemTXZhuBoChecked {
            get {
                return ((bool)(this["ItemTXZhuBoChecked"]));
            }
            set {
                this["ItemTXZhuBoChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ItemTXGeLiDuChecked {
            get {
                return ((bool)(this["ItemTXGeLiDuChecked"]));
            }
            set {
                this["ItemTXGeLiDuChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ItemSwitchSpeedChecked {
            get {
                return ((bool)(this["ItemSwitchSpeedChecked"]));
            }
            set {
                this["ItemSwitchSpeedChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ItemTXChaSunChecked {
            get {
                return ((bool)(this["ItemTXChaSunChecked"]));
            }
            set {
                this["ItemTXChaSunChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GPIB0::16::INSTR")]
        public string AVGPIBAddress {
            get {
                return ((string)(this["AVGPIBAddress"]));
            }
            set {
                this["AVGPIBAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GPIB0::1::INSTR")]
        public string OSCGPIBAddress {
            get {
                return ((string)(this["OSCGPIBAddress"]));
            }
            set {
                this["OSCGPIBAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AVPresetScript {
            get {
                return ((string)(this["AVPresetScript"]));
            }
            set {
                this["AVPresetScript"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("未校准")]
        public string STDRXChaSun1 {
            get {
                return ((string)(this["STDRXChaSun1"]));
            }
            set {
                this["STDRXChaSun1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("未校准")]
        public string STDTXChaSun1 {
            get {
                return ((string)(this["STDTXChaSun1"]));
            }
            set {
                this["STDTXChaSun1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("未校准")]
        public string STDRXChaSun2 {
            get {
                return ((string)(this["STDRXChaSun2"]));
            }
            set {
                this["STDRXChaSun2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("未校准")]
        public string STDTXChaSun2 {
            get {
                return ((string)(this["STDTXChaSun2"]));
            }
            set {
                this["STDTXChaSun2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("未校准")]
        public string STDRXChaSun3 {
            get {
                return ((string)(this["STDRXChaSun3"]));
            }
            set {
                this["STDRXChaSun3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("未校准")]
        public string STDTXChaSun3 {
            get {
                return ((string)(this["STDTXChaSun3"]));
            }
            set {
                this["STDTXChaSun3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.8")]
        public string FreqMark1 {
            get {
                return ((string)(this["FreqMark1"]));
            }
            set {
                this["FreqMark1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string FreqMark2 {
            get {
                return ((string)(this["FreqMark2"]));
            }
            set {
                this["FreqMark2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.5")]
        public string FreqMark3 {
            get {
                return ((string)(this["FreqMark3"]));
            }
            set {
                this["FreqMark3"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RX插损")]
        public string LabelRXChaSun {
            get {
                return ((string)(this["LabelRXChaSun"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TX插损")]
        public string LabelTXChaSun {
            get {
                return ((string)(this["LabelTXChaSun"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RX驻波")]
        public string LabelRXZhuBo {
            get {
                return ((string)(this["LabelRXZhuBo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TX驻波")]
        public string LabelTXZhuBo {
            get {
                return ((string)(this["LabelTXZhuBo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TX隔离度")]
        public string LabelTXGeLiDu {
            get {
                return ((string)(this["LabelTXGeLiDu"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RX隔离度")]
        public string LabelRXGeLiDu {
            get {
                return ((string)(this["LabelRXGeLiDu"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LabelSwitchSpeed {
            get {
                return ((string)(this["LabelSwitchSpeed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TX耐功率")]
        public string LabelTxNaiGongLu {
            get {
                return ((string)(this["LabelTxNaiGongLu"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RX耐功率")]
        public string LabelRxNaiGongLu {
            get {
                return ((string)(this["LabelRxNaiGongLu"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AVPreset {
            get {
                return ((int)(this["AVPreset"]));
            }
            set {
                this["AVPreset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.8")]
        public string ThreshRxChaSun {
            get {
                return ((string)(this["ThreshRxChaSun"]));
            }
            set {
                this["ThreshRxChaSun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public string ThreshRxGeLiDu {
            get {
                return ((string)(this["ThreshRxGeLiDu"]));
            }
            set {
                this["ThreshRxGeLiDu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.3")]
        public string ThreshZhuBo {
            get {
                return ((string)(this["ThreshZhuBo"]));
            }
            set {
                this["ThreshZhuBo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("46")]
        public string ThreshPowerResist {
            get {
                return ((string)(this["ThreshPowerResist"]));
            }
            set {
                this["ThreshPowerResist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string ThreshSwitchSpeed {
            get {
                return ((string)(this["ThreshSwitchSpeed"]));
            }
            set {
                this["ThreshSwitchSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ItemTXNaiGongLu {
            get {
                return ((bool)(this["ItemTXNaiGongLu"]));
            }
            set {
                this["ItemTXNaiGongLu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string TC1Zero {
            get {
                return ((string)(this["TC1Zero"]));
            }
            set {
                this["TC1Zero"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string TC2Zero {
            get {
                return ((string)(this["TC2Zero"]));
            }
            set {
                this["TC2Zero"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string TC1Tool {
            get {
                return ((string)(this["TC1Tool"]));
            }
            set {
                this["TC1Tool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string TC2Tool {
            get {
                return ((string)(this["TC2Tool"]));
            }
            set {
                this["TC2Tool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00")]
        public string CtrlCodeZero {
            get {
                return ((string)(this["CtrlCodeZero"]));
            }
            set {
                this["CtrlCodeZero"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("52")]
        public string CtrlCodeTool {
            get {
                return ((string)(this["CtrlCodeTool"]));
            }
            set {
                this["CtrlCodeTool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E")]
        public string CtrlCodeRXChaSunZhuBo {
            get {
                return ((string)(this["CtrlCodeRXChaSunZhuBo"]));
            }
            set {
                this["CtrlCodeRXChaSunZhuBo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4E")]
        public string CtrlCodeRXGeLiDu {
            get {
                return ((string)(this["CtrlCodeRXGeLiDu"]));
            }
            set {
                this["CtrlCodeRXGeLiDu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0D0A")]
        public string CtrlCodeRXNaiGongLu {
            get {
                return ((string)(this["CtrlCodeRXNaiGongLu"]));
            }
            set {
                this["CtrlCodeRXNaiGongLu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("52")]
        public string CtrlCodeTXChaSunZhuBo {
            get {
                return ((string)(this["CtrlCodeTXChaSunZhuBo"]));
            }
            set {
                this["CtrlCodeTXChaSunZhuBo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0AB1")]
        public string CtrlCodeTXGeLiDu {
            get {
                return ((string)(this["CtrlCodeTXGeLiDu"]));
            }
            set {
                this["CtrlCodeTXGeLiDu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("71")]
        public string CtrlCodeTXNaiGongLu {
            get {
                return ((string)(this["CtrlCodeTXNaiGongLu"]));
            }
            set {
                this["CtrlCodeTXNaiGongLu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("41")]
        public string CtrlCodeSystemPower {
            get {
                return ((string)(this["CtrlCodeSystemPower"]));
            }
            set {
                this["CtrlCodeSystemPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SwitchControlAddr {
            get {
                return ((int)(this["SwitchControlAddr"]));
            }
            set {
                this["SwitchControlAddr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("450")]
        public int ItemSwitchHoldTime {
            get {
                return ((int)(this["ItemSwitchHoldTime"]));
            }
            set {
                this["ItemSwitchHoldTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("54")]
        public int ColNoWidth {
            get {
                return ((int)(this["ColNoWidth"]));
            }
            set {
                this["ColNoWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int ColRXChaSunWidth {
            get {
                return ((int)(this["ColRXChaSunWidth"]));
            }
            set {
                this["ColRXChaSunWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int ColRXZhuBoWidth {
            get {
                return ((int)(this["ColRXZhuBoWidth"]));
            }
            set {
                this["ColRXZhuBoWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int ColRXGeLiDuWidth {
            get {
                return ((int)(this["ColRXGeLiDuWidth"]));
            }
            set {
                this["ColRXGeLiDuWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int ColRXNaiGongLuWidth {
            get {
                return ((int)(this["ColRXNaiGongLuWidth"]));
            }
            set {
                this["ColRXNaiGongLuWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int ColTXChaSunWidth {
            get {
                return ((int)(this["ColTXChaSunWidth"]));
            }
            set {
                this["ColTXChaSunWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int ColTxZhuBoWidth {
            get {
                return ((int)(this["ColTxZhuBoWidth"]));
            }
            set {
                this["ColTxZhuBoWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int ColTxGeLiDuWidth {
            get {
                return ((int)(this["ColTxGeLiDuWidth"]));
            }
            set {
                this["ColTxGeLiDuWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int ColTxNaiGongLuWidth {
            get {
                return ((int)(this["ColTxNaiGongLuWidth"]));
            }
            set {
                this["ColTxNaiGongLuWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int ColSwitchSpeedWidth {
            get {
                return ((int)(this["ColSwitchSpeedWidth"]));
            }
            set {
                this["ColSwitchSpeedWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("811, 710")]
        public global::System.Drawing.Size MainFrameClientSize {
            get {
                return ((global::System.Drawing.Size)(this["MainFrameClientSize"]));
            }
            set {
                this["MainFrameClientSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoRecall {
            get {
                return ((bool)(this["AutoRecall"]));
            }
            set {
                this["AutoRecall"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int chOfRxChaSun {
            get {
                return ((int)(this["chOfRxChaSun"]));
            }
            set {
                this["chOfRxChaSun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int chOfRXZhuBo {
            get {
                return ((int)(this["chOfRXZhuBo"]));
            }
            set {
                this["chOfRXZhuBo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int chOfRxGeLiDu {
            get {
                return ((int)(this["chOfRxGeLiDu"]));
            }
            set {
                this["chOfRxGeLiDu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int chOfRxNaiGongLu {
            get {
                return ((int)(this["chOfRxNaiGongLu"]));
            }
            set {
                this["chOfRxNaiGongLu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int chOfTxChaSun {
            get {
                return ((int)(this["chOfTxChaSun"]));
            }
            set {
                this["chOfTxChaSun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int chOfTXZhuBo {
            get {
                return ((int)(this["chOfTXZhuBo"]));
            }
            set {
                this["chOfTXZhuBo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int chOfTxGeLiDu {
            get {
                return ((int)(this["chOfTxGeLiDu"]));
            }
            set {
                this["chOfTxGeLiDu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int chOfTxNaiGongLu {
            get {
                return ((int)(this["chOfTxNaiGongLu"]));
            }
            set {
                this["chOfTxNaiGongLu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MainFrameLoc {
            get {
                return ((global::System.Drawing.Point)(this["MainFrameLoc"]));
            }
            set {
                this["MainFrameLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string STDRXGeLiDu1 {
            get {
                return ((string)(this["STDRXGeLiDu1"]));
            }
            set {
                this["STDRXGeLiDu1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string STDRXGeLiDu2 {
            get {
                return ((string)(this["STDRXGeLiDu2"]));
            }
            set {
                this["STDRXGeLiDu2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string STDRXGeLiDu3 {
            get {
                return ((string)(this["STDRXGeLiDu3"]));
            }
            set {
                this["STDRXGeLiDu3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string STDTXGeLiDu1 {
            get {
                return ((string)(this["STDTXGeLiDu1"]));
            }
            set {
                this["STDTXGeLiDu1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string STDTXGeLiDu2 {
            get {
                return ((string)(this["STDTXGeLiDu2"]));
            }
            set {
                this["STDTXGeLiDu2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string STDTXGeLiDu3 {
            get {
                return ((string)(this["STDTXGeLiDu3"]));
            }
            set {
                this["STDTXGeLiDu3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OptionPageSelected {
            get {
                return ((int)(this["OptionPageSelected"]));
            }
            set {
                this["OptionPageSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public string STDRXGeLiDu {
            get {
                return ((string)(this["STDRXGeLiDu"]));
            }
            set {
                this["STDRXGeLiDu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-0.4")]
        public string ThreshTxChaSun {
            get {
                return ((string)(this["ThreshTxChaSun"]));
            }
            set {
                this["ThreshTxChaSun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("856694")]
        public string PassWord {
            get {
                return ((string)(this["PassWord"]));
            }
            set {
                this["PassWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("未校准")]
        public string STDTXNaiGongLu {
            get {
                return ((string)(this["STDTXNaiGongLu"]));
            }
            set {
                this["STDTXNaiGongLu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("未校准")]
        public string STDRXNaiGongLu {
            get {
                return ((string)(this["STDRXNaiGongLu"]));
            }
            set {
                this["STDRXNaiGongLu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShutDownSwitchAfterTestItem {
            get {
                return ((bool)(this["ShutDownSwitchAfterTestItem"]));
            }
            set {
                this["ShutDownSwitchAfterTestItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int SwitchOffMillisecond {
            get {
                return ((int)(this["SwitchOffMillisecond"]));
            }
            set {
                this["SwitchOffMillisecond"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("54")]
        public string CtrlCodeTxPreTxPower {
            get {
                return ((string)(this["CtrlCodeTxPreTxPower"]));
            }
            set {
                this["CtrlCodeTxPreTxPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("54")]
        public string CtrlCodeTxPostTxPower {
            get {
                return ((string)(this["CtrlCodeTxPostTxPower"]));
            }
            set {
                this["CtrlCodeTxPostTxPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowNotPassedRecord {
            get {
                return ((bool)(this["ShowNotPassedRecord"]));
            }
            set {
                this["ShowNotPassedRecord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool waitForToolConfirm {
            get {
                return ((bool)(this["waitForToolConfirm"]));
            }
            set {
                this["waitForToolConfirm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string TxPowerFreq {
            get {
                return ((string)(this["TxPowerFreq"]));
            }
            set {
                this["TxPowerFreq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("46")]
        public string ExternalTxPowerCaliValue {
            get {
                return ((string)(this["ExternalTxPowerCaliValue"]));
            }
            set {
                this["ExternalTxPowerCaliValue"] = value;
            }
        }
    }
}
